# NOTE: Generated By HttpRunner v3.1.4
# FROM: har/mubu.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMubu(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/login")
            .get("https://mubu.com/login")
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.2128988841.1608641787",
                    "use-redesign": "1",
                    "data_unique_id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "csrf_token": "762cc766-44fb-4f17-9339-6ecbd32b9b2f",
                    "SESSION": "865b6bb0-74ea-462c-9cd8-230fa65fe133",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.1940696041.1617714709",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1617714709",
                    "reg_focusId": "cd407dba-7bfa-4ab1-b6f1-178a753b4a0",
                    "reg_prepareId": "178a753d934-178a753b444-4ab1-b6f1-cad67392bf74",
                    "SLARDAR_WEB_ID": "c4dfa9db-d57f-47f4-81ca-4b1f45634302",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1617715099",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/login/password")
            .get("https://mubu.com/login/password")
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/login",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.2128988841.1608641787",
                    "use-redesign": "1",
                    "data_unique_id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "csrf_token": "762cc766-44fb-4f17-9339-6ecbd32b9b2f",
                    "SESSION": "865b6bb0-74ea-462c-9cd8-230fa65fe133",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.1940696041.1617714709",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1617714709",
                    "SLARDAR_WEB_ID": "e233f8cf-bb7f-42f4-934b-ac80465bb9d8",
                    "_gat": "1",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1617715211",
                    "reg_focusId": "5660d1ed-62db-43ae-881c-178a757583d",
                    "reg_prepareId": "178a757598e-178a7572a87-43ae-881c-45ac0007fd23",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/api/login/submit")
            .post("https://mubu.com/api/login/submit")
            .with_headers(
                **{
                    "content-length": "52",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "accept": "application/json, text/javascript, */*; q=0.01",
                    "x-requested-with": "XMLHttpRequest",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.2128988841.1608641787",
                    "use-redesign": "1",
                    "data_unique_id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "csrf_token": "762cc766-44fb-4f17-9339-6ecbd32b9b2f",
                    "SESSION": "865b6bb0-74ea-462c-9cd8-230fa65fe133",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.1940696041.1617714709",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1617714709",
                    "_gat": "1",
                    "reg_focusId": "5660d1ed-62db-43ae-881c-178a757583d",
                    "reg_prepareId": "178a757598e-178a7572a87-43ae-881c-45ac0007fd23",
                    "SLARDAR_WEB_ID": "b02c2e6f-dd32-48f6-8e80-908a7537644a",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1617715225",
                }
            )
            .with_data(
                {"phone": "13153117137", "password": "yaoyingdong", "remember": "true"}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/app")
            .get("https://mubu.com/app")
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-user": "?1",
                    "sec-fetch-dest": "document",
                    "referer": "https://mubu.com/login/password",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_cookies(
                **{
                    "_ga": "GA1.2.2128988841.1608641787",
                    "use-redesign": "1",
                    "data_unique_id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "csrf_token": "762cc766-44fb-4f17-9339-6ecbd32b9b2f",
                    "SESSION": "865b6bb0-74ea-462c-9cd8-230fa65fe133",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "language": "en-US",
                    "country": "US",
                    "_gid": "GA1.2.1940696041.1617714709",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1617714709",
                    "_gat": "1",
                    "reg_focusId": "5660d1ed-62db-43ae-881c-178a757583d",
                    "reg_prepareId": "178a757598e-178a7572a87-43ae-881c-45ac0007fd23",
                    "SLARDAR_WEB_ID": "b02c2e6f-dd32-48f6-8e80-908a7537644a",
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1617715225",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTAyOTQwNDQiLCJleHAiOjE2MjAzMDcyNDMsImlhdCI6MTYxNzcxNTI0M30.ZvQcSFnb-uOs2aVqwTMmS2moqfeHHxPHaygPCqGEKSbbdhykRTag2PI4pauWWEEL_IeazAVKllCjdpN3Rxd7Sg",
                    "user_persistence": "2d932be9-2c9c-40e2-89f7-d1eba197df5b",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/user/profile")
            .post("https://api2.mubu.com/v3/api/user/profile")
            .with_headers(
                **{
                    "content-length": "0",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "data-unique-id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTAyOTQwNDQiLCJleHAiOjE2MjAzMDcyNDMsImlhdCI6MTYxNzcxNTI0M30.ZvQcSFnb-uOs2aVqwTMmS2moqfeHHxPHaygPCqGEKSbbdhykRTag2PI4pauWWEEL_IeazAVKllCjdpN3Rxd7Sg",
                    "x-request-id": "4d0dba21-b39f-4519-b16d-1588acb1d621",
                    "version": "3.0.0.21310",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "30",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "data-unique-id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTAyOTQwNDQiLCJleHAiOjE2MjAzMDcyNDMsImlhdCI6MTYxNzcxNTI0M30.ZvQcSFnb-uOs2aVqwTMmS2moqfeHHxPHaygPCqGEKSbbdhykRTag2PI4pauWWEEL_IeazAVKllCjdpN3Rxd7Sg",
                    "x-request-id": "91285ef5-1d48-422e-bf00-0c63a74d9b43",
                    "version": "3.0.0.21310",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/get")
            .post("https://api2.mubu.com/v3/api/list/get")
            .with_headers(
                **{
                    "content-length": "58",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "data-unique-id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTAyOTQwNDQiLCJleHAiOjE2MjAzMDcyNDMsImlhdCI6MTYxNzcxNTI0M30.ZvQcSFnb-uOs2aVqwTMmS2moqfeHHxPHaygPCqGEKSbbdhykRTag2PI4pauWWEEL_IeazAVKllCjdpN3Rxd7Sg",
                    "x-request-id": "6008844f-38b5-45f9-8eb1-e129d0dba22d",
                    "version": "3.0.0.21310",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {"folderId": 0, "sort": "time", "keywords": "", "source": "home"}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/get_all_documents_page")
            .post("https://api2.mubu.com/v3/api/list/get_all_documents_page")
            .with_headers(
                **{
                    "content-length": "12",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "data-unique-id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTAyOTQwNDQiLCJleHAiOjE2MjAzMDcyNDMsImlhdCI6MTYxNzcxNTI0M30.ZvQcSFnb-uOs2aVqwTMmS2moqfeHHxPHaygPCqGEKSbbdhykRTag2PI4pauWWEEL_IeazAVKllCjdpN3Rxd7Sg",
                    "x-request-id": "2dcc7caf-5dc5-49a6-ab47-5e2f08465528",
                    "version": "3.0.0.21310",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"start": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/star_relation/get")
            .get("https://api2.mubu.com/v3/api/list/star_relation/get")
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "data-unique-id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTAyOTQwNDQiLCJleHAiOjE2MjAzMDcyNDMsImlhdCI6MTYxNzcxNTI0M30.ZvQcSFnb-uOs2aVqwTMmS2moqfeHHxPHaygPCqGEKSbbdhykRTag2PI4pauWWEEL_IeazAVKllCjdpN3Rxd7Sg",
                    "x-request-id": "e5ed47e8-4637-4ce8-965b-a85a8512d2b9",
                    "version": "3.0.0.21310",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/message/get_message_unread")
            .post("https://api2.mubu.com/v3/api/message/get_message_unread")
            .with_headers(
                **{
                    "content-length": "10",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "data-unique-id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTAyOTQwNDQiLCJleHAiOjE2MjAzMDcyNDMsImlhdCI6MTYxNzcxNTI0M30.ZvQcSFnb-uOs2aVqwTMmS2moqfeHHxPHaygPCqGEKSbbdhykRTag2PI4pauWWEEL_IeazAVKllCjdpN3Rxd7Sg",
                    "x-request-id": "8f7e9e12-e46e-4102-a388-3134ac930625",
                    "version": "3.0.0.21310",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"page": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_user_params")
            .post("https://api2.mubu.com/v3/api/user/get_user_params")
            .with_headers(
                **{
                    "content-length": "0",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "data-unique-id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTAyOTQwNDQiLCJleHAiOjE2MjAzMDcyNDMsImlhdCI6MTYxNzcxNTI0M30.ZvQcSFnb-uOs2aVqwTMmS2moqfeHHxPHaygPCqGEKSbbdhykRTag2PI4pauWWEEL_IeazAVKllCjdpN3Rxd7Sg",
                    "x-request-id": "4fc8589b-e5be-458c-a1a9-c4407869b60c",
                    "version": "3.0.0.21310",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "30",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "data-unique-id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTAyOTQwNDQiLCJleHAiOjE2MjAzMDcyNDMsImlhdCI6MTYxNzcxNTI0M30.ZvQcSFnb-uOs2aVqwTMmS2moqfeHHxPHaygPCqGEKSbbdhykRTag2PI4pauWWEEL_IeazAVKllCjdpN3Rxd7Sg",
                    "x-request-id": "91285ef5-1d48-422e-bf00-0c63a74d9b43",
                    "version": "3.0.0.21310",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/create_folder")
            .options("https://api2.mubu.com/v3/api/list/create_folder")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,version,x-request-id",
                    "origin": "https://mubu.com",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/list/create_folder")
            .post("https://api2.mubu.com/v3/api/list/create_folder")
            .with_headers(
                **{
                    "content-length": "30",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "data-unique-id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTAyOTQwNDQiLCJleHAiOjE2MjAzMDcyNDMsImlhdCI6MTYxNzcxNTI0M30.ZvQcSFnb-uOs2aVqwTMmS2moqfeHHxPHaygPCqGEKSbbdhykRTag2PI4pauWWEEL_IeazAVKllCjdpN3Rxd7Sg",
                    "x-request-id": "56751715-75e3-4cad-91a5-a84de47751a0",
                    "version": "3.0.0.21310",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"name": "demo", "folderId": "0"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "41",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "data-unique-id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTAyOTQwNDQiLCJleHAiOjE2MjAzMDcyNDMsImlhdCI6MTYxNzcxNTI0M30.ZvQcSFnb-uOs2aVqwTMmS2moqfeHHxPHaygPCqGEKSbbdhykRTag2PI4pauWWEEL_IeazAVKllCjdpN3Rxd7Sg",
                    "x-request-id": "3eb0179d-333c-49d2-a0ad-ebc259b84411",
                    "version": "3.0.0.21310",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": "OF005ecDAs", "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/create_doc")
            .options("https://api2.mubu.com/v3/api/list/create_doc")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,version,x-request-id",
                    "origin": "https://mubu.com",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/list/create_doc")
            .post("https://api2.mubu.com/v3/api/list/create_doc")
            .with_headers(
                **{
                    "content-length": "34",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "data-unique-id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTAyOTQwNDQiLCJleHAiOjE2MjAzMDcyNDMsImlhdCI6MTYxNzcxNTI0M30.ZvQcSFnb-uOs2aVqwTMmS2moqfeHHxPHaygPCqGEKSbbdhykRTag2PI4pauWWEEL_IeazAVKllCjdpN3Rxd7Sg",
                    "x-request-id": "ecc81a0c-0997-4d23-ba29-ac48c63c3840",
                    "version": "3.0.0.21310",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": "OF005ecDAs", "type": 0})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "30",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "data-unique-id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTAyOTQwNDQiLCJleHAiOjE2MjAzMDcyNDMsImlhdCI6MTYxNzcxNTI0M30.ZvQcSFnb-uOs2aVqwTMmS2moqfeHHxPHaygPCqGEKSbbdhykRTag2PI4pauWWEEL_IeazAVKllCjdpN3Rxd7Sg",
                    "x-request-id": "cb82b7c0-4139-487b-bb8c-f6e6a29b54a5",
                    "version": "3.0.0.21310",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/current_level")
            .options("https://api2.mubu.com/v3/api/user/current_level")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,version,x-request-id",
                    "origin": "https://mubu.com",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/document/edit/get")
            .options("https://api2.mubu.com/v3/api/document/edit/get")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,version,x-request-id",
                    "origin": "https://mubu.com",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/user/current_level")
            .post("https://api2.mubu.com/v3/api/user/current_level")
            .with_headers(
                **{
                    "content-length": "29",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "data-unique-id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTAyOTQwNDQiLCJleHAiOjE2MjAzMDcyNDMsImlhdCI6MTYxNzcxNTI0M30.ZvQcSFnb-uOs2aVqwTMmS2moqfeHHxPHaygPCqGEKSbbdhykRTag2PI4pauWWEEL_IeazAVKllCjdpN3Rxd7Sg",
                    "x-request-id": "41e153e3-ee41-46ab-b5c8-d607f72a5c76",
                    "version": "3.0.0.21310",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"document_id": "1ruLvNloKAs"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/document/edit/get")
            .post("https://api2.mubu.com/v3/api/document/edit/get")
            .with_headers(
                **{
                    "content-length": "37",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "data-unique-id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTAyOTQwNDQiLCJleHAiOjE2MjAzMDcyNDMsImlhdCI6MTYxNzcxNTI0M30.ZvQcSFnb-uOs2aVqwTMmS2moqfeHHxPHaygPCqGEKSbbdhykRTag2PI4pauWWEEL_IeazAVKllCjdpN3Rxd7Sg",
                    "x-request-id": "f2ea5066-a901-44a0-924a-836474f96f6d",
                    "version": "3.0.0.21310",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"docId": "1ruLvNloKAs", "password": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/doc/list")
            .options("https://api2.mubu.com/v3/api/refer/doc/list")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,x-request-id",
                    "origin": "https://mubu.com",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/register")
            .options("https://api2.mubu.com/v3/api/colla/register")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "GET",
                    "access-control-request-headers": "data-unique-id,jwt-token,x-request-id",
                    "origin": "https://mubu.com",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/refer/doc/list")
            .post("https://api2.mubu.com/v3/api/refer/doc/list")
            .with_headers(
                **{
                    "content-length": "29",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "data-unique-id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTAyOTQwNDQiLCJleHAiOjE2MjAzMDcyNDMsImlhdCI6MTYxNzcxNTI0M30.ZvQcSFnb-uOs2aVqwTMmS2moqfeHHxPHaygPCqGEKSbbdhykRTag2PI4pauWWEEL_IeazAVKllCjdpN3Rxd7Sg",
                    "x-request-id": "f60d695c-22d1-4dd3-87b4-f2fcf805718e",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"targetDocId": "1ruLvNloKAs"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/register")
            .get("https://api2.mubu.com/v3/api/colla/register")
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTAyOTQwNDQiLCJleHAiOjE2MjAzMDcyNDMsImlhdCI6MTYxNzcxNTI0M30.ZvQcSFnb-uOs2aVqwTMmS2moqfeHHxPHaygPCqGEKSbbdhykRTag2PI4pauWWEEL_IeazAVKllCjdpN3Rxd7Sg",
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "data-unique-id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "x-request-id": "dbf6cadf-ffd5-4e5a-b85a-c73977759c54",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/node/count")
            .options("https://api2.mubu.com/v3/api/refer/node/count")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,version,x-request-id",
                    "origin": "https://mubu.com",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/refer/node/count")
            .post("https://api2.mubu.com/v3/api/refer/node/count")
            .with_headers(
                **{
                    "content-length": "29",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "data-unique-id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTAyOTQwNDQiLCJleHAiOjE2MjAzMDcyNDMsImlhdCI6MTYxNzcxNTI0M30.ZvQcSFnb-uOs2aVqwTMmS2moqfeHHxPHaygPCqGEKSbbdhykRTag2PI4pauWWEEL_IeazAVKllCjdpN3Rxd7Sg",
                    "x-request-id": "50615340-9f35-4145-aef6-242e80295985",
                    "version": "3.0.0.21310",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"targetDocId": "1ruLvNloKAs"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .options("https://api2.mubu.com/v3/api/colla/members")
            .with_params(
                **{"memberId": "1920268403178882", "documentId": "1ruLvNloKAs"}
            )
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "GET",
                    "access-control-request-headers": "data-unique-id,jwt-token,request-id,x-request-id",
                    "origin": "https://mubu.com",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/members")
            .get("https://api2.mubu.com/v3/api/colla/members")
            .with_params(
                **{"memberId": "1920268403178882", "documentId": "1ruLvNloKAs"}
            )
            .with_headers(
                **{
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "data-unique-id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTAyOTQwNDQiLCJleHAiOjE2MjAzMDcyNDMsImlhdCI6MTYxNzcxNTI0M30.ZvQcSFnb-uOs2aVqwTMmS2moqfeHHxPHaygPCqGEKSbbdhykRTag2PI4pauWWEEL_IeazAVKllCjdpN3Rxd7Sg",
                    "request-id": "members:1920268403178882:1617715255282",
                    "x-request-id": "bf079985-c7d7-4a7a-800a-8b8498fbecda",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .options("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,member-id,request-id,version,x-request-id",
                    "origin": "https://mubu.com",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "568",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "1920268403178882",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "data-unique-id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTAyOTQwNDQiLCJleHAiOjE2MjAzMDcyNDMsImlhdCI6MTYxNzcxNTI0M30.ZvQcSFnb-uOs2aVqwTMmS2moqfeHHxPHaygPCqGEKSbbdhykRTag2PI4pauWWEEL_IeazAVKllCjdpN3Rxd7Sg",
                    "request-id": "MESSAGE:10294044:1920268403178882:3",
                    "x-request-id": "9a9474d4-2947-48e9-affb-25264cd00355",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 3,
                    "requestId": "MESSAGE:10294044:1920268403178882:3",
                    "token": "1ruLvNloKAs",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "1ruLvNloKAs",
                            "version": 0,
                            "content": [
                                {"name": "nameChanged", "title": "t", "original": ""},
                                {"name": "nameChanged", "title": "ti", "original": "t"},
                                {
                                    "name": "nameChanged",
                                    "title": "tit",
                                    "original": "ti",
                                },
                                {
                                    "name": "nameChanged",
                                    "title": "titl",
                                    "original": "tit",
                                },
                                {
                                    "name": "nameChanged",
                                    "title": "title",
                                    "original": "titl",
                                },
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "11.1.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "456",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "1920268403178882",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "data-unique-id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTAyOTQwNDQiLCJleHAiOjE2MjAzMDcyNDMsImlhdCI6MTYxNzcxNTI0M30.ZvQcSFnb-uOs2aVqwTMmS2moqfeHHxPHaygPCqGEKSbbdhykRTag2PI4pauWWEEL_IeazAVKllCjdpN3Rxd7Sg",
                    "request-id": "MESSAGE:10294044:1920268403178882:5",
                    "x-request-id": "1016faea-4789-4016-972b-44e41df84f9d",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 5,
                    "requestId": "MESSAGE:10294044:1920268403178882:5",
                    "token": "1ruLvNloKAs",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "1ruLvNloKAs",
                            "version": 1,
                            "content": [
                                {
                                    "name": "create",
                                    "created": [
                                        {
                                            "index": 0,
                                            "parentId": None,
                                            "node": {
                                                "id": "g6n2flc0oQ",
                                                "text": "",
                                                "modified": 1617715256714,
                                                "children": [],
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "11.1.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/refer/search_refers")
            .options("https://api2.mubu.com/v3/api/refer/search_refers")
            .with_headers(
                **{
                    "accept": "*/*",
                    "access-control-request-method": "POST",
                    "access-control-request-headers": "content-type,data-unique-id,jwt-token,x-request-id",
                    "origin": "https://mubu.com",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/refer/search_refers")
            .post("https://api2.mubu.com/v3/api/refer/search_refers")
            .with_headers(
                **{
                    "content-length": "53",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "data-unique-id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTAyOTQwNDQiLCJleHAiOjE2MjAzMDcyNDMsImlhdCI6MTYxNzcxNTI0M30.ZvQcSFnb-uOs2aVqwTMmS2moqfeHHxPHaygPCqGEKSbbdhykRTag2PI4pauWWEEL_IeazAVKllCjdpN3Rxd7Sg",
                    "x-request-id": "489af55a-5de2-44e7-8027-fc9dff477768",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"docId": "1ruLvNloKAs", "keywords": "title", "option": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "502",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "1920268403178882",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "data-unique-id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTAyOTQwNDQiLCJleHAiOjE2MjAzMDcyNDMsImlhdCI6MTYxNzcxNTI0M30.ZvQcSFnb-uOs2aVqwTMmS2moqfeHHxPHaygPCqGEKSbbdhykRTag2PI4pauWWEEL_IeazAVKllCjdpN3Rxd7Sg",
                    "request-id": "MESSAGE:10294044:1920268403178882:7",
                    "x-request-id": "8416f4dd-b794-4a4e-b494-173cd5f482aa",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "BROADCAST",
                    "reqId": 7,
                    "requestId": "MESSAGE:10294044:1920268403178882:7",
                    "token": "1ruLvNloKAs",
                    "data": {
                        "message": {
                            "type": "CHANGE",
                            "documentId": "1ruLvNloKAs",
                            "version": 2,
                            "content": [
                                {
                                    "name": "update",
                                    "updated": [
                                        {
                                            "updated": {
                                                "id": "g6n2flc0oQ",
                                                "text": "<span>demo</span>",
                                                "modified": 1617715259517,
                                            },
                                            "original": {
                                                "id": "g6n2flc0oQ",
                                                "text": "",
                                                "modified": 1617715256714,
                                            },
                                            "path": ["nodes", 0],
                                        }
                                    ],
                                }
                            ],
                        }
                    },
                    "context": {
                        "os": "macOS",
                        "osVersion": "11.1.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "content-length": "41",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "data-unique-id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTAyOTQwNDQiLCJleHAiOjE2MjAzMDcyNDMsImlhdCI6MTYxNzcxNTI0M30.ZvQcSFnb-uOs2aVqwTMmS2moqfeHHxPHaygPCqGEKSbbdhykRTag2PI4pauWWEEL_IeazAVKllCjdpN3Rxd7Sg",
                    "x-request-id": "51761de1-2a7d-4b3e-8e9f-1437daa124f1",
                    "version": "3.0.0.21310",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json({"folderId": "OF005ecDAs", "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/colla/message")
            .post("https://api2.mubu.com/v3/api/colla/message")
            .with_headers(
                **{
                    "content-length": "225",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "member-id": "1920268403178882",
                    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36",
                    "data-unique-id": "2b7540fa-9d38-4f6f-9bae-9096fb781618",
                    "content-type": "application/json;charset=UTF-8",
                    "accept": "application/json, text/plain, */*",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTAyOTQwNDQiLCJleHAiOjE2MjAzMDcyNDMsImlhdCI6MTYxNzcxNTI0M30.ZvQcSFnb-uOs2aVqwTMmS2moqfeHHxPHaygPCqGEKSbbdhykRTag2PI4pauWWEEL_IeazAVKllCjdpN3Rxd7Sg",
                    "request-id": "MESSAGE:10294044:1920268403178882:10",
                    "x-request-id": "ad1f541c-a015-4346-9309-d5ddb5402604",
                    "version": "3.0.0",
                    "origin": "https://mubu.com",
                    "sec-fetch-site": "same-site",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-dest": "empty",
                    "referer": "https://mubu.com/",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                }
            )
            .with_json(
                {
                    "engineType": "MUBU",
                    "messageType": "UNWATCH",
                    "reqId": 10,
                    "requestId": "MESSAGE:10294044:1920268403178882:10",
                    "token": "1ruLvNloKAs",
                    "data": {},
                    "context": {
                        "os": "macOS",
                        "osVersion": "11.1.0",
                        "appVersion": "default",
                        "platform": "web",
                    },
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseMubu().test_start()
